### ISSUE TITLE
Exit to Home Menu is broken on FW 4.1.0

### ISSUE THREAD

**Issue by Nougat-Police** [dimok789/homebrew_launcher#3] opened 2016-03-09 17:10 UTC
Sorry, didn't realize this as a bug first. When you press home button in HBL main menu the screen fades out as should but then freezes with a black screen. WiiU needs to be powered off hard.

Exit, Pause and Resume are broken on FW 4.1.0 and probably below.

**UDP log:**
Starting launcher
Function exports loaded
Initialize memory management
Mount SD partition
Start main application
Initialize video
Video size 1280 x 720
Initialize main font system
Initialize main window
Entering main loop
_[pressing home button]_
Main application stopped
Destroy music
Destroy controller
Destroy async deleter
Clear resources
Stop sound handler
Unmount SD
Release memory

**Comment by dimok789** [comment] 2016-03-11 09:06
Ok, thanks for the report. Maybe the address of the entry point is wrong or the acquire function? It was wrong on 5.0.0/5.1.0 too. See here https://github.com/wiiudev/libwiiu/commit/7c5395f2fd518af3ab2320cff64c78a5112323f6
That was causing exactly that kind of issue on 5.0.0.

Maybe also check if those two addresses are correct:
#define ADDRESS_OSTitle_main_entry_ptr              0x1005A8C0
#define ADDRESS_main_entry_hook                       0x0101BD4C

HBL jumps to the addresses pointed to by the pointer at ADDRESS_OSTitle_main_entry_ptr on exit to mii maker or the others.

**Comment by Nougat-Police** [comment] 2016-03-12 15:01
Hi, I checked everything and all addresses are correct. Furthermore I figured out that the issue is something sound related like on 500. At this time I have no clue were the problem is located exactly, so I just removed the sound feature. HBL and loadiine GX2 are working now.

**Comment by dimok789** [comment] 2016-03-13 21:15
Maybe the issue is that I use sound core 2 library which was added as a replacement for sound core 1 library at some point. I am not sure if 4.0.0 already had that library. Maybe it was somewhat different on 4.0.0?

**Comment by Nougat-Police** [comment] 2016-03-13 21:38
Yes, this .rpl exists on 4.0.0. I also looked through ax_functions.c and all functions there are available on 4.0.0 too.

**Comment by dimok789** [comment] 2016-04-22 05:12
@andriy921 fixed that issue. I will merged his pull request and will do an official release of v1.2 with the support for fw 4.0.0-5.0.0 with proper sound feature support. Please test it before I do the release today in the evening but I am positive it will work now.

**Closed by dimok789** 2016-04-22 05:12 UTC
